export const QuestionsList = {
  QuestionsList10: [
    {
      index: 1,
      Questions: 'What shape is the earth',
      answer: {
        A: 'Circle',
        B: 'Squaer',
        C: 'Ellipse',
        D: 'Globular',
      },
      rightAnswer: 'D',
    },
    {
      index: 2,
      Questions: 'What is the name of the tallest mountain in the world?',
      answer: {
        A: 'Mount Everest',
        B: 'Mount K2',
        C: 'Mount Kanchenjunga',
        D: 'Mount Lhotse',
      },
      rightAnswer: 'A',
    },
    {
      index: 3,
      Questions: 'Which country has the largest population in the world?',
      answer: {
        A: 'Russia',
        B: 'China',
        C: 'Korean',
        D: 'France',
      },
      rightAnswer: 'B',
    },
    {
      index: 4,
      Questions: 'What are the names of the seven continents of the world?',
      answer: {
        A: 'Asia, Africa, North America, North America, Antarctica, Europe, Australia',
        B: 'Asia, Africa, America North, South America, Antarctica, Europe, Australia',
        C: 'Asia, Africa, North America, South America, Antarctica, Europe',
        D: 'Asia, Africa, North America, South America, Antarctica, Europe, Australia',
      },
      rightAnswer: 'D',
    },
    {
      index: 5,
      Questions: 'What is the name of the longest river in Africa?',
      answer: {
        A: 'The Nile River',
        B: 'The Amazon River',
        C: 'The Niger River',
        D: 'The Zambezi River',
      },
      rightAnswer: 'A',
    },
    {
      index: 6,
      Questions: 'What American city is the Golden Gate Bridge located in?',
      answer: {
        A: 'San Francisco',
        B: 'New York',
        C: 'Los Angeles',
        D: 'Ha Noi',
      },
      rightAnswer: 'A',
    },
    {
      index: 7,
      Questions: 'Where is the Eiffel Tower located?',
      answer: {
        A: 'Paris',
        B: 'Ho Chi Minh',
        C: 'Tokyo',
        D: 'Beijing',
      },
      rightAnswer: 'A',
    },
    {
      index: 8,
      Questions: 'What is the capital of Canada?',
      answer: {
        A: 'Tirana',
        B: 'Yerevan',
        C: 'Ottawa',
        D: 'Warsaw',
      },
      rightAnswer: 'C',
    },
    {
      index: 9,
      Questions: 'What is the name of the largest ocean in the world?',
      answer: {
        A: 'The Pacific Ocean',
        B: 'The Atlantic Ocean',
        C: 'The Indian Ocean',
        D: 'The Southern Ocean',
      },
      rightAnswer: 'A',
    },
    {
      index: 10,
      Questions: 'What is the name of the smallest country in the world?',
      answer: {
        A: 'The Vatican City',
        B: 'VietNam',
        C: 'Nauru',
        D: 'Tuvalu',
      },
      rightAnswer: 'A',
    },
    {
      index: 11,
      Questions: 'What country has the most natural lakes?',
      answer: {
        A: 'Azerbaijan',
        B: 'Canada',
        C: 'Russia',
        D: 'Brazil',
      },
      rightAnswer: 'B',
    },
  ],
  QuestionsList20: [
    {
      index: 1,
      Questions: 'What planet is closest to Earth?',
      answer: {
        A: 'Venus',
        B: 'Mercury',
        C: 'Mars',
        D: 'Saturn',
      },
      rightAnswer: 'A',
    },
    {
      index: 2,
      Questions:
        'What is the name of the river that flows through the Brazil rainforest?',
      answer: {
        A: 'The Mekong River',
        B: 'The Amazon',
        C: 'Yangtze River',
        D: 'Mississippi',
      },
      rightAnswer: 'B',
    },
    {
      index: 3,
      Questions: 'Which country is also called The Netherlands?',
      answer: {
        A: 'VietNam',
        B: 'Japan',
        C: 'Brazil',
        D: 'Holland',
      },
      rightAnswer: 'D',
    },
    {
      index: 4,
      Questions: 'What is the coldest place on Earth?',
      answer: {
        A: 'Arctica',
        B: 'Shahara',
        C: 'Antarctica',
        D: 'Mediterranean',
      },
      rightAnswer: 'C',
    },
    {
      index: 5,
      Questions: 'What is the official currency of the United Kingdom?',
      answer: {
        A: 'yuan',
        B: 'USD',
        C: 'Euro',
        D: 'Pound sterling',
      },
      rightAnswer: 'D',
    },
    {
      index: 6,
      Questions: 'What country lies above Mexico?',
      answer: {
        A: 'The United States of America',
        B: 'England',
        C: 'Canada',
        D: 'Korea',
      },
      rightAnswer: 'A',
    },
    {
      index: 7,
      Questions: 'How many countries are there in the United Kingdom?',
      answer: {
        A: '5',
        B: '4',
        C: '3',
        D: '2',
      },
      rightAnswer: 'B',
    },
    {
      index: 8,
      Questions: 'What is the capital of Senegal?',
      answer: {
        A: 'Pra-ha',
        B: 'Madrid',
        C: 'Dakar',
        D: 'Humburg',
      },
      rightAnswer: 'C',
    },
    {
      index: 9,
      Questions: 'How many time zones does Russia have?',
      answer: {
        A: '11',
        B: '7',
        C: '10',
        D: '5',
      },
      rightAnswer: 'A',
    },
    {
      index: 10,
      Questions: 'What is the name of the tallest mountain in Canada?',
      answer: {
        A: 'Mount Edith Cavell',
        B: 'Mount Logan',
        C: 'Sulphur Mountain',
        D: 'Mount Temple',
      },
      rightAnswer: 'B',
    },
    {
      index: 11,
      Questions: 'What country does the Rhine River run through?',
      answer: {
        A: 'Portugal',
        B: 'Iatalia',
        C: 'France',
        D: 'Germany',
      },
      rightAnswer: 'D',
    },
    {
      index: 12,
      Questions:
        'What is the name of the second tallest mountain in the world?',
      answer: {
        A: 'K2',
        B: 'Fansipan',
        C: 'Alps',
        D: 'Fuji',
      },
      rightAnswer: 'A',
    },
    {
      index: 12,
      Questions: 'Who won the first nobel prize?',
      answer: {
        A: 'Philipp Lenard',
        B: 'J. J. Thomson',
        C: 'Wilhelm Conrad Röntgen',
        D: 'Pieter Zeeman',
      },
      rightAnswer: 'C',
    },
    {
      index: 13,
      Questions: 'The world population reached 7 billion in what year?',
      answer: {
        A: '2011',
        B: '2009',
        C: '2012',
        D: '2013',
      },
      rightAnswer: 'A',
    },
    {
      index: 14,
      Questions: 'Snakes belong to which class?',
      answer: {
        A: 'Mammalia',
        B: 'Insecta',
        C: 'Reptile',
        D: 'Amphibians',
      },
      rightAnswer: 'C',
    },
    {
      index: 15,
      Questions: 'Snakes belong to which class?',
      answer: {
        A: 'Mammalia',
        B: 'Insecta',
        C: 'Reptile',
        D: 'Amphibians',
      },
      rightAnswer: 'C',
    },
    {
      index: 16,
      Questions: 'How many countries does the equator pass through?',
      answer: {
        A: '20',
        B: '13',
        C: '12',
        D: '17',
      },
      rightAnswer: 'B',
    },
    {
      index: 17,
      Questions: 'In what year was the first iPhone released?',
      answer: {
        A: '2007',
        B: '2006',
        C: '2008',
        D: '2009',
      },
      rightAnswer: 'A',
    },
    {
      index: 18,
      Questions: 'In what year was the United Nations born?',
      answer: {
        A: '24/10/1946',
        B: '24/9/1945',
        C: '02/10/1945',
        D: '24/10/1945',
      },
      rightAnswer: 'D',
    },
    {
      index: 19,
      Questions: 'How many countries are there in Asia?',
      answer: {
        A: '50',
        B: '54',
        C: '55',
        D: '49',
      },
      rightAnswer: 'C',
    },
    {
      index: 20,
      Questions: 'How far is the earth from the moon?',
      answer: {
        A: 'approximately 200,000 km',
        B: 'approximately 300,000 km',
        C: 'approximately 400,000 km',
        D: 'approximately 500,000 km',
      },
      rightAnswer: 'C',
    },
    {
      index: 21,
      Questions: 'Which country has the longest coastline?',
      answer: {
        A: 'Canada',
        B: 'Indonesia',
        C: 'Russia',
        D: 'Greenland',
      },
      rightAnswer: 'A',
    },
  ],
  QuestionsList30: [
    {
      index: 1,
      Questions: 'What shape is the earth 30',
      answer: {
        A: '30',
        B: '3',
        C: '4',
        D: '5',
      },
      rightAnswer: 'D',
    },
  ],
};
